# Generated by Django 5.0.1 on 2024-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_surname', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_position', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff/')),
            ],
        ),
    ]
